{{- if .Values.ollama.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ollama.name" . }}
  labels:
    {{- include "ollama.labels" . | nindent 4 }}
  {{- with .Values.ollama.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ollama.ingress.class }}
  ingressClassName: {{ .Values.ollama.ingress.class | quote }}
  {{- end }}
  {{- if .Values.ollama.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ollama.ingress.host | quote }}
      secretName: {{ .Values.ollama.ingress.existingSecret | default (printf "%s-tls" (include "ollama.name" .)) }}
  {{- end }}
  rules:
    - host: {{ .Values.ollama.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "ollama.name" . }}
                port:
                  number: 80
{{- end -}}
